apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.service_name }}
    template: {{ .Values.service_name }}
  name: {{ .Values.service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service_name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        last-updated-epoch: {{ now | unixEpoch | quote }}
      labels:
        app: {{ .Values.service_name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secret_name }}
      containers:
      - image: {{ .Values.docker_image }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
        name: {{ .Values.service_name }}
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          limits:
            cpu: 2
            memory: 4Gi 
          requests:
            cpu: 2
            memory: 4Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
