{{- if eq .Values.deployment_target "kubernetes" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: {{ .Values.service_name }}
    template: {{ .Values.service_name }}
  name: {{ .Values.service_name }}
spec:
  tls:
  - hosts:
    - {{ .Values.service_url }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.service_url }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.service_name }}
              port:
                number: 8080
{{- end }}
