{{- if eq .Values.deployment_target "openshift" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.service_name }}
    template: {{ .Values.service_name }}
  name: {{ .Values.service_name }}
spec:
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge     
  to:
    kind: Service
    name: {{ .Values.service_name }}
{{- end }}