apiVersion: v1
kind: Service
metadata:
  annotations:
    description: {{ .Values.service_name }} http port
  labels:
    app: {{ .Values.service_name }}
    template: {{ .Values.service_name }}
  name: {{ .Values.service_name }}
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.service_name }}
  sessionAffinity: None
  type: ClusterIP