/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.myproj.ublcii.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import reactor.core.publisher.Mono;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;

import org.springframework.core.io.Resource;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-05-21T13:41:33.184Z[GMT]")
@Validated
public interface UBLCIIApi {

	@Operation(summary = "POST Operation for UBL2CII Conversion", description = "Convert a valid XML invoice from UBL2CII format.", tags = {
			"UBLCII API" })
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Resource.class))),
			@ApiResponse(responseCode = "400", description = "Bad Request", content = @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class))),
			@ApiResponse(responseCode = "500", description = "Internal Server Error", content = @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class))) })
	@PostMapping(value = "/ubl2cii", consumes = MediaType.MULTIPART_FORM_DATA_VALUE, produces = MediaType.APPLICATION_OCTET_STREAM_VALUE
			+ ";" + MediaType.TEXT_PLAIN_VALUE)
	Mono<ResponseEntity<Resource>> postUBLCII(
			@Parameter(description = "Upload valid XML file for conversion") @RequestPart("uploadFile") MultipartFile file);

}
